name: Test workflow
on: push
jobs:
    job1:
        runs-on: self-hosted
        steps:
            - name: Display info
              run: |
                echo "Job ID: ${{ github.job }}"
                echo "Job workflow SHA: ${{ github.job_workflow_sha }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run attempt: ${{ github.run_attempt }}"
                echo "Run number: ${{ github.run_number }}"
                echo "Actor: ${{ github.actor }}"
                echo "Actor ID: ${{ github.actor_id }}"
                echo "Event: ${{ github.event }}"
                echo "Event name: ${{ github.event_name }}"
                echo "Event path: ${{ github.event_path }}"
                echo "Trigger actor: ${{ github.triggering_actor}}"
                echo "Commit: ${{ github.sha}}"

    job2:
        runs-on: self-hosted
        steps:
            - name: Display info
              run: |
                echo "Job ID: ${{ github.job }}"
                echo "Job workflow SHA: ${{ github.job_workflow_sha }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run attempt: ${{ github.run_attempt }}"
                echo "Run number: ${{ github.run_number }}"
                echo "Actor: ${{ github.actor }}"
                echo "Actor ID: ${{ github.actor_id }}"
                echo "Event: ${{ github.event }}"
                echo "Event name: ${{ github.event_name }}"
                echo "Event path: ${{ github.event_path }}"
                echo "Trigger actor: ${{ github.triggering_actor }}"
                echo "Commit: ${{ github.sha }}"

    job3:
        runs-on: self-hosted
        steps:
            - name: Display info
              run: |
                echo "Job ID: ${{ github.job }}"
                echo "Job workflow SHA: ${{ github.job_workflow_sha }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run attempt: ${{ github.run_attempt }}"
                echo "Run number: ${{ github.run_number }}"
                echo "Actor: ${{ github.actor }}"
                echo "Actor ID: ${{ github.actor_id }}"
                echo "Event: ${{ github.event }}"
                echo "Event name: ${{ github.event_name }}"
                echo "Event path: ${{ github.event_path }}"
                echo "Trigger actor: ${{ github.triggering_actor}}"
                echo "Commit: ${{ github.sha }}"

    job4:
        runs-on: self-hosted
        steps:
            - name: Display info
              run: |
                echo "Job ID: ${{ github.job }}"
                echo "Job workflow SHA: ${{ github.job_workflow_sha }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run attempt: ${{ github.run_attempt }}"
                echo "Run number: ${{ github.run_number }}"
                echo "Actor: ${{ github.actor }}"
                echo "Actor ID: ${{ github.actor_id }}"
                echo "Event: ${{ github.event }}"
                echo "Event name: ${{ github.event_name }}"
                echo "Event path: ${{ github.event_path }}"
                echo "Trigger actor: ${{ github.triggering_actor}}"
                echo "Commit: ${{ github.sha }}"